<?php
/**
 * Finix Color Customization
 *
 * @package Finix
 * @subpackage finix
 * @since finix 1.0
 */

function finix_color_customization() {  
    
    $dynamic_css = '';

    $finix_opt = get_option('finix_redux');

    $primary_color = $finix_opt['primary_color'];
    $primary_gradient_color = $finix_opt['primary_gradient_color'];
    $secondary_color = $finix_opt['secondary_color'];
    $tertiary_color = $finix_opt['tertiary_color'];
   

    /********************************************* 
    Theme Color Option
    *********************************************/ 
    // Primary Color
    if( !empty($primary_color)) {

        // Text Color
        $dynamic_css .="
        .swiper-container .swiper-button-next:hover i, 
        .swiper-container .swiper-button-prev:hover i,
        .arrow-style3 .swiper-container .swiper-button-next i,
        .arrow-style3 .swiper-container .swiper-button-prev i,
        .site-header .feature-box.icon-left .feature-icon i,
        .site-header .feature-box a:hover, 
        .main-navigation .navbar-nav > li.current-menu-ancestor > a,
        .main-navigation .navbar-nav > li.current-menu-parent > a,
        .main-navigation .navbar-nav > li:hover > a, 
        .main-navigation .navbar-nav > li > a:hover, 
        .main-navigation .navbar-nav > li.current-menu-item > a,
        .main-navigation .navbar-nav li .sub-menu li:hover > a, 
        .main-navigation .navbar-nav li .sub-menu li > a:hover, 
        .main-navigation .navbar-nav li .sub-menu li.current-menu-item > a,
        .main-navigation .navbar-nav li .sub-menu li.current-menu-item:hover > a,
        .site-header .header-search .search-btn:hover,
        .site-header .slicknav_nav li.current-menu-item > a,
        .site-header .slicknav_nav li.current-menu-ancestor > a > a,
        .site-header.header-fancy .header-inner .feature-box .feature-icon i,
        .page-header-inner.page-header-2 .breadcrumb li > a:hover, 
        .page-header-inner.page-header-2 .breadcrumb li > span a:hover,
        .elementor-section .elementor-widget-text-editor a,
        .elementor-section .elementor-text-editor a,
        .post-meta ul li i,
        .post-meta ul li a:hover,
        article.post .post-title .title a:hover,
        article.page .post-title .title a:hover,
        article.team .post-title .title a:hover,
        article.portfolio .post-title .title a:hover,
        .site-content blockquote:before,
        .site-content blockquote cite,
        .comment-respond .comment-reply-title a,
        .widget ul li > a:hover,
        .widget.widget_recent_comments li.recentcomments .comment-author-link a:hover,
        .widget_recent_post .recent-post-list .post-info .post-date,
        .widget_recent_post .recent-post-list .post-info .post-title:hover,
        .widget.widget_search .search-form .search-submit, 
        .widget_social_media .social-info.style-default.color-theme li a,
        .widget_social_media .social-info.style-border.color-theme li a,
        .widget_contact .footer-address ul li i,
        .widget_feature_info .widget-feature-icon i,
        .widget .menu-service-menu-container ul li.current-menu-item a,
        .widget .menu-service-menu-container ul li a:hover,
        .footer-info-social li a:hover,
        .search-no-results .site-content .search-form .search-submit,
        .wc-block-product-search .wc-block-product-search__fields .wc-block-product-search__button,
        .error-404-main .error-text a,
        .error-404-main .search-form .search-submit,
        .error-404-main .text-404 .inner-text,
        .title-coming-soon .coming-soon-inner,
        .entry-content .is-style-outline .wp-block-button__link:not(.has-text-color),
        article.post a, 
        article.post th a:hover, 
        article.page a, 
        article.page th a:hover,
        article.post .read-more,
        article.page .read-more,
        article.team .read-more,
        article.portfolio .read-more,
        .site-content blockquote:after,
        .wpcf7-form .wpcf7-submit:hover,
        .finix-profile-cover .author-bio .author-social-media li a:hover,
        .comments-area .comment-details .comment-description a,
        .comments-area .comment-details .comment-description td a:hover,
        .comments-area .comment-details .author-info .comment-meta i,
        .comment-respond .comment-form .logged-in-as a,
        .comment-respond .comment-form .form-submit .submit:hover,
        .team-detail-info .contact-details ul li i,
        .team-detail-info .contact-info .social-info ul li a,
        .team-detail-info .personal-info .user-position,
        .single-team .user-quote:before,
        .team-detail-info .contact-info .social-info .social-icon,
        .comments-area .commentlist .trackback a,
        .comments-area .commentlist .pingback a,
        .single-post .recent-post .latest-post .post-content .post-title a:hover,
        .single-post .recent-post .latest-post .post-link .read-more,
        .site-header:not(.sticky) .button-theme:hover,
        .site-header:not(.sticky) .button-border.button-theme,
        .site-header:not(.sticky) .header-button .button-flat.button-gradient:hover,
        .site-header:not(.sticky) .button-border.button-gradient,
        .site-header.sticky .header-button .header-link:hover,
        .widget.widget_archive ul li, 
        .widget.widget_categories ul li,
        .wc-block-product-categories ul li,
        .widget.widget_rss li .rss-date,
        .widget .calendar_wrap tbody td a,
        .widget.widget_calendar .wp-calendar-nav a:hover,
        article.post .entry-social .social-list li a:hover,
        .single-post .blog-content .post-navigation .nav-subtitle,
        .single-post .blog-content .post-navigation .post-title:hover,
        .widget .wp-block-categories li a:before,
        .widget.widget_categories ul li a:before,
        .wc-block-product-categories ul li a:before,

        .section-title .title-tagline,
        .feature-box .feature-icon i,
        .feature-box .feature-link,
        .feature-box.style-border .feature-icon i,
        .list.icon-default li i,
        .list.icon-border li i,
        .counter-default .counter-icon,
        .counter .suffix,
        .btn-default.style-default,
        .btn-default.style-border,
        .tab.tab-style1 .nav-tabs .nav-link.active,
        .tab.tab-style2 .nav-tabs .nav-link i,
        .pricing-table .pricing-icon i,
        .pricing-table .pricing-list li i,
        .pricing-table .pricing-button .style-border,
        .social-icons.style-default li a,
        .social-icons.style-border li a,
        .blog-style-1 .post-inner .post-content .meta-date i,
        .blog-style-1 .post-inner .post-content .meta-author a:hover,
        .blog-post-main .post-inner .post-content .post-title a:hover,
        .blog-style-2 .post-inner .post-content .read-link,
        .blog-style-3 .post-inner .post-link .read-link:hover,
        .blog-style-3 .post-inner .post-meta a:hover,
        .blog-style-3 .post-inner .post-meta i,
        .team-member .member-info .member-position,
        .team-member .member-info .member-name a:hover,
        .team-member .team-social ul li a:hover,
        .team-member.team-style-5 .team-member-inner .member-name a:hover,
        .testimonial-main.testimonial-style-1 .testimonial-inner .icon-quote,
        .testimonial-main.testimonial-style-2 .author-details .author-position,
        .testimonial-main.testimonial-style-2 .testimonial-inner .icon-quote,
        .testimonial-main.testimonial-style-3 .testimonial-inner .icon-quote,
        .small-feature .feature-inner .feature-icon i,
        .small-feature.feature-style-2 .feature-inner .feature-icon i,
        .small-feature.feature-style-2 .feature-inner .feature-bg-icon,
        .features-step.step-style-1 .step-icon,
        .portfolio-main .portfolio-style-2 .item-info .popup-link,
        .portfolio-main .grid-item .item-info .portfolio-title .title-link:hover,
        .portfolio-main .portfolio-wrapper .b-isotope-filter.filter-style-2 li.current a,
        .portfolio-main .portfolio-wrapper .b-isotope-filter.filter-style-3 li.current a,
        .portfolio-main .portfolio-style-3 .item-info .popup-link,
        .portfolio-main .portfolio-style-3 .item-info .portfolio-category,
        .single-portfolio .navigation .nav-links .nav-text,
        .single-portfolio .navigation a:hover .post-title,
        .style-border .video-button,
        .single-portfolio .recent-portfolio .latest-portfolio .portfolio-content .portfolio-title a:hover,
        .single-portfolio .recent-portfolio .latest-portfolio .portfolio-content .portfolio-category,
        .entry-content .wp-block-rss li a:hover, 
        .entry-content .wp-block-latest-posts li a:hover,
        .web-host-list ul li span,

        .widget li .count,
        .site-header .header-cart-btn a:hover,
        .site-header .header-search .search-btn:hover,
        .single-product .summary .woocommerce-review-link:hover,
        .single-product .summary .yith-wcwl-add-to-wishlist .yith-wcwl-wishlistexistsbrowse a:hover,
        .single-product div.product .summary .product_meta .sku:hover,
        .single-product div.product .summary .product_meta .posted_in a:hover,
        .single-product div.product .summary .product_meta .tagged_as a:hover,
        .woocommerce #review_form #respond .form-submit input:hover,
        .woocommerce-cart table.shop_table td.actions .button:hover,
        .woocommerce-cart .cart-collaterals .cart_totals .checkout-button:hover,
        .woocommerce-checkout .woocommerce-form-coupon .button:hover,
        .woocommerce-checkout .woocommerce-form-login .button:hover,
        .woocommerce-account .woocommerce-form-login .button:hover,
        .woocommerce-account .woocommerce-form-register .button:hover,
        .woocommerce-cart .return-to-shop .button:hover,
        .woocommerce-cart table.shop_table .product-name a:hover,
        .woocommerce-cart .cart-collaterals .cart_totals .order-total .amount,
        .woocommerce-checkout .woocommerce-checkout .order-total .amount,
        .woocommerce-order .woocommerce-order-details .shop_table tfoot .amount,
        .woocommerce-account .woocommerce-MyAccount-navigation li.is-active a,
        .woocommerce-account .woocommerce-MyAccount-navigation li a:hover,
        .woocommerce-account .woocommerce-MyAccount-content .woocommerce-pagination .woocommerce-button:hover,
        .woocommerce-account .woocommerce-MyAccount-content .edit-account .woocommerce-Button:hover,
        .site-header .mini-cart-content .woocommerce-mini-cart__total .woocommerce-Price-amount,
        .widget_shopping_cart .woocommerce-mini-cart__total .woocommerce-Price-amount,
        .woocommerce .woocommerce-layout .finix-switch-layout a:hover,
        .widget .wc-block-attribute-filter li .wc-block-attribute-filter-list-count,
        .widget_rating_filter li.wc-layered-nav-rating a,
        .widget_rating_filter li.wc-layered-nav-rating a:hover .star-rating,
        .finix-form-element .form-link,
        .finix-form-element .form-main-title span,
        .finix-form-element.after-login .form-link:hover,
        .quick-info .info-text span,
        .quick-info .info-text a:hover,

        .page-header .breadcrumb li span,
        .page-header .breadcrumb li a:hover,
        .page-header-inner.page-header-2 .breadcrumb li > a:hover,
        .page-header-inner.page-header-2 .breadcrumb li > span a:hover {color:$primary_color; }";

        // Border Color
        $dynamic_css .="
            .mouse-cursor.cursor-outer,
            article.post.sticky, 
            article.post.tag-sticky-2,
            .pagination li .current, 
            .pagination li a:hover,
            .btn-default.style-border,
            .wpcf7-form .wpcf7-submit,
            .comment-respond .comment-form .form-submit .submit,
            .wpcf7-form .wpcf7-form-control-wrap input:focus,
            .wpcf7-form .wpcf7-form-control-wrap select:focus,
            .wpcf7-form .wpcf7-form-control-wrap textarea:focus,
            .form-style-border .wpcf7-form-control-wrap input:focus,
            .form-style-border .wpcf7-form-control-wrap select:focus, 
            .form-style-border .wpcf7-form-control-wrap textarea:focus,
            .swiper-container .swiper-pagination-bullet.swiper-pagination-bullet-active:before,
            .portfolio-main .portfolio-wrapper .b-isotope-filter.filter-style-3 li.current a,
            .portfolio-main .portfolio-style-3 .item-info .popup-link:hover,
            .style-border .video-button,
            .style-border.pulse-effect-active .video-button:before,
            .style-border.pulse-effect-active .video-button:after,
            .site-header:not(.sticky) .button-theme:after,
            .site-header:not(.sticky) .button-gradient:after,
            .site-header.sticky .header-button .header-link:after,
            .comment-respond .comment-form .comment-form-author input:focus,
            .comment-respond .comment-form .comment-form-email input:focus,
            .comment-respond .comment-form .comment-form-url input:focus,
            .comment-respond .comment-form .comment-form-comment textarea:focus,
            .widget.widget_tag_cloud ul li a:hover,
            .widget.widget_tag_cloud .wp-block-tag-cloud a:hover,
            .widget_product_tag_cloud .tagcloud a:hover,
            .single-post .entry-content .wp-block-tag-cloud a:hover,
            .newsletter-main.newsletter-style-2 .input-area input:focus,

            .woocommerce nav.woocommerce-pagination ul li a:focus,
            .woocommerce nav.woocommerce-pagination ul li a:hover,
            .woocommerce nav.woocommerce-pagination ul li span.current,
            .woocommerce .site-content div.product .woocommerce-tabs ul.wc-tabs li.active a,
            .woocommerce #review_form #respond .form-submit input,
            .woocommerce-cart table.shop_table td.actions .button,
            .woocommerce-cart .cart-collaterals .cart_totals .checkout-button,
            .woocommerce-checkout .woocommerce-form-coupon .button,
            .woocommerce-checkout .woocommerce-form-login .button,
            .woocommerce-account .woocommerce-form-login .button,
            .woocommerce-account .woocommerce-form-register .button,
            .woocommerce-account .woocommerce-MyAccount-content .woocommerce-pagination .woocommerce-button,
            .woocommerce-account .woocommerce-MyAccount-content .edit-account .woocommerce-Button,
            .single-product .summary .variations_form .variations .value select:focus,
            .woocommerce-cart #content table.shop_table td.actions .coupon .input-text:focus,
            .woocommerce-cart table.shop_table td.actions .coupon .input-text:focus,
            .woocommerce-checkout .woocommerce-form-login .input-text:focus,
            .woocommerce-checkout .woocommerce-form-coupon .input-text:focus,
            .woocommerce-account .woocommerce-form-login .input-text:focus,
            .woocommerce-account .woocommerce-form-register .input-text:focus,
            .woocommerce-cart .return-to-shop .button,
            .woocommerce-checkout .woocommerce-billing-fields .form-row .input-text:focus,
            .woocommerce-checkout .woocommerce-additional-fields .form-row .input-text:focus,
            .woocommerce-checkout .woocommerce-billing-fields .form-row .select2-container .select2-selection--single:focus,
            .woocommerce-account .woocommerce-MyAccount-content .edit-account .input-text:focus,
            .finix-form-element.after-login .form-link {border-color:$primary_color;}";

        // Border Top Color
        $dynamic_css .="
            .tab.tab-style2 .nav-tabs .nav-link.active:after,
            .widget_testimonial .testimonial-inner .author-content:before,
            .pricing-table.pricing-1.selected {border-top-color:$primary_color;}";

        // Border Bottom Color
        $dynamic_css .="
            .section-title .title-tagline:before,
            .team-member.team-style-1 .member-info,
            .team-detail-info .personal-info .user-position:before,
            .single-portfolio .navigation .nav-previous .nav-text:before, 
            .single-portfolio .navigation .nav-next .nav-text:before,
            .portfolio-main .portfolio-wrapper .b-isotope-filter.filter-style-2 li.current a,
            .single-post .blog-content .post-navigation .nav-subtitle:before,
            .single-post .blog-content .post-navigation .nav-subtitle:before {border-bottom-color:$primary_color;}";

        // Border Left Color
        $dynamic_css .="
            .site-content blockquote,
            .widget .menu-service-menu-container ul li.current-menu-item a,
            .widget .menu-service-menu-container ul li a:hover,
            .sidebar .widget .widget-title,
            .elementor-column .widget .widget-title,
            .sidebar .widget .wp-block-group__inner-container > h2,
            .sidebar .widget .wp-block-woocommerce-attribute-filter > h3,
            .woocommerce-account .woocommerce-MyAccount-navigation li.is-active a,
            .woocommerce-account .woocommerce-MyAccount-navigation li a:hover {border-left-color:$primary_color !important;}";

        // Stroke Color
        $dynamic_css .="
            .error-404-main .text-404,
            .title-coming-soon {-webkit-text-stroke-color: $primary_color;}";


        // Background Color
        $dynamic_css .="
            .swiper-container .swiper-button-next i, 
            .swiper-container .swiper-button-prev i,
            .arrow-style3 .swiper-container .swiper-button-next:hover i,
            .arrow-style3 .swiper-container .swiper-button-prev:hover i,
            .swiper-container .swiper-pagination-bullet.swiper-pagination-bullet-active,
            #back-to-top .top,
            .mouse-cursor.cursor-inner,
            .cursor-outer.cursor-hover,
            .main-navigation .navbar-nav > li > a:before,
            .main-navigation .navbar-nav li .sub-menu li a:before,
            .site-header .header-sidemenu:hover span,
            .site-header .slicknav_nav li.slicknav_open > a .slicknav_arrow,
            .site-header.header-classic:not(.sticky) .header-bottom .header-button .button-theme,
            article.post .blog-media .post-categery,
            article.post .blog-media blockquote, 
            article.page .blog-media blockquote,
            .pagination li .current, 
            .pagination li a:hover,
            article.post .read-more:before,
            article.page .read-more:before,
            article.team .read-more:before,
            article.portfolio .read-more:before,
            article.post .read-more:after,
            article.page .read-more:after,
            article.team .read-more:after,
            article.portfolio .read-more:after,
            .wpcf7-form .wpcf7-submit,
            .entry-content .page-links > a:hover, 
            .entry-content .page-links > span.current,
            .comment-respond .comment-form .form-submit .submit,
            .entry-content .wp-block-button .wp-block-button__link,
            .comments-area .comment-details .reply a:hover,
            .post-password-form p > input,
            .wp-block-search .wp-block-search__button,
            .widget_social_media .social-info.style-flat.color-theme li a,
            .widget_testimonial .testimonial-inner .author-content,
            .widget_newsletter .button-area button,
            .team-detail-info .user-experience,
            .team-detail-info .contact-info .contact-btn a:hover,
            .wp-block-calendar table th,
            .single-post .entry-content .wp-block-tag-cloud a:hover,
            .single-post .recent-post .latest-post .post-image .meta-date,
            .single-post .recent-post .latest-post .post-link .read-more:before, 
            .single-post .recent-post .latest-post .post-link .read-more:after,
            .single-portfolio .recent-portfolio .latest-portfolio .portfolio-content .portfolio-link,
            .site-header:not(.sticky) .button-theme:before,
            .site-header:not(.sticky) .button-gradient:before,
            .site-header.sticky .header-button .header-link:before,
            .widget.widget_tag_cloud ul li a:hover,
            .widget.widget_tag_cloud .wp-block-tag-cloud a:hover,
            .widget_product_tag_cloud .tagcloud a:hover,
            .widget .calendar_wrap caption,
            .widget .calendar_wrap #today,

            .section-title .divider,
            .section-title.sub_title-2 .title-tagline,
            .feature-box.style-flat .feature-icon i,
            .feature-box.style-shadow:hover,
            .feature-box .feature-link:after, 
            .feature-box .feature-link:before,
            .feature-box.border-hover:before,
            .feature-box.style-icon-bg .feature-icon:after,
            .testimonial-main.testimonial-style-2 .author-photo .quote,
            .list.icon-flat li i,
            .skill .progress-bar,
            .btn-default.style-default:after, 
            .btn-default.style-default:before,
            .btn-default.style-flat,
            .btn-default.style-border:before,
            .tab.tab-style1 .nav-tabs .nav-link:before,
            .tab.tab-style2 .nav-tabs .nav-link.active,
            .tab.tab-style3 .nav-tabs .nav-link.active,
            .pricing-table .pricing-button .style-flat,
            .pricing-table .pricing-button .style-border:hover,
            .pricing-table.pricing-2.selected,
            .pricing-table.pricing-4.selected .pricing-header,
            .pricing-table.pricing-4 .pricing-title,
            .social-icons.style-border li a:hover,
            .social-icons.style-flat li a,
            .blog-post-main .post-inner .post-category,
            .blog-style-3 .post-image .meta-date,
            .team-member.team-style-1 .member-info:before,
            .team-member.team-style-3 .member-inner,
            .team-member.team-style-4 .member-info:before,
            .team-member.team-style-5 .team-social ul li a,
            .small-feature.feature-style-1:hover .feature-inner,
            .small-feature.feature-style-2:hover .feature-inner,
            .features-step.step-style-1 .icons-info .step-number,
            .features-step.step-style-1 .icons-info .step-number:before,
            .features-step.step-style-2 .step-number,
            .features-step.step-style-2 .step-number:before,
            .portfolio-main .portfolio-style-1 .portfolio-item .portfolio-control,
            .portfolio-main .portfolio-wrapper .b-isotope-filter.filter-style-1 li.current a,
            .portfolio-main .portfolio-style-3 .item-info .popup-link:hover,
            .video-button,
            .style-flat.pulse-effect-active .video-button:before,
            .newsletter-main .button-area button,
            .maintance-main .button-area button,
            .coming-soon-main .button-area button,
            .wp24-dc #dc-result-1 .table .table-row,
            .web-host-list ul li:hover,

            .site-header .header-cart-btn a span,
            .woocommerce ul.products li.product .product-block-inner .product-thumbnail .button,
            .woocommerce nav.woocommerce-pagination ul li a:focus,
            .woocommerce nav.woocommerce-pagination ul li a:hover,
            .woocommerce nav.woocommerce-pagination ul li span.current,
            .woocommerce #review_form #respond .form-submit input,
            .woocommerce_status_bar .status-steps-item.active span.num,
            .woocommerce-cart table.shop_table td.actions .button,
            .woocommerce-cart .cart-collaterals .cart_totals .checkout-button,
            .woocommerce-checkout .woocommerce-form-coupon .button,
            .woocommerce-checkout .woocommerce-form-login .button,
            .woocommerce-account .woocommerce-form-login .button,
            .woocommerce-account .woocommerce-form-register .button,
            .woocommerce-cart .return-to-shop .button,
            .woocommerce-checkout #order_review #payment #place_order:hover,
            .woocommerce-account .woocommerce-MyAccount-content .woocommerce-pagination .woocommerce-button,
            .woocommerce-account .woocommerce-MyAccount-content .edit-account .woocommerce-Button,
            .site-header .mini-cart-content .woocommerce-mini-cart__buttons .button:hover,
            .widget_shopping_cart .woocommerce-mini-cart__buttons .button:hover,
            .widget_price_filter .price_slider_wrapper .ui-slider-horizontal .ui-slider-range,
            .widget_price_filter .price_slider_wrapper .ui-slider .ui-slider-handle,
            .widget_product_search .woocommerce-product-search button[type=submit],
            .finix-form-element.after-login .form-link,
            .quick-info .small-images i,
            .demo-item .builder-button .demo-button:hover {background:$primary_color; }";
    
        // Background Gradient Color
        if( !empty($primary_gradient_color)) {
            $dynamic_css .="
                #back-to-top .top,
                .bottom-navbar .mobile-navbar-bg,
                .sidemenu-main .sidemenu-button a,
                .site-header.header-classic .header-bottom .navigation-inner,
                .page-header-inner.page-header-2 .breadcrumb li > .current-page,
                article.post .blog-media blockquote, 
                article.page .blog-media blockquote,
                .search-main .search-form .search-field,
                .skill .progress-bar,
                .pricing-table.pricing-2.selected,
                .pricing-table.pricing-4.selected .pricing-header,
                .team-member.team-style-1 .member-info:before,
                .team-member.team-style-3 .member-inner,
                .team-member.team-style-4 .member-info:before,
                .site-header:not(.sticky) .button-gradient:before,
                .site-header.sticky .header-button .header-link:before,
                .site-header.header-classic:not(.sticky) .header-bottom .header-button .button-gradient {background-image:linear-gradient(to right, $primary_color 0%, $primary_gradient_color 100%) }";

        // Background Gradient Color
        if( !empty($primary_gradient_color)) {
            $dynamic_css .="
                .mobile-navbar_activated .bottom-navbar .mobile-navbar-bg { background: linear-gradient(180deg, rgba(255,255,255,0) 20%, $primary_color 70%)}"; 
                }
        }
    }

    // Secondary Color
    if( !empty($secondary_color)) {
        // Text Color
        $dynamic_css .="
            h1, h2, h3, h4, h5, h6,
            pre,
            .sidebar .widget .widget-title,
            .sidebar .widget .widget-title,
            .elementor-column .widget .widget-title,
            .sidebar .widget .wp-block-group__inner-container > h2,
            .sidebar .widget .wp-block-woocommerce-attribute-filter > h3,
            article.post .post-title .title a,
            .pagination li a,
            .pagination li span,
            .entry-content .page-links > a, 
            .entry-content .page-links > span,
            .error-404-main .error-tagline,
            article.post th a, 
            article.page td a,
            .widget.widget_rss li a,
            .site-content blockquote,
            article.post .entry-social .social-list li a,
            .finix-profile-cover .author-bio .author-social-media li a, 
            .comments-area .comment-details .reply a,
            .comments-area .comment-details .author-info .author-name,
            .comments-area .comment-details .author-info .author-name a,
            .comments-area .comment-details .comment-description td a,
            .comments-area .comment-details .author-info .author-name a,
            .single-post .recent-post .latest-post .post-content .post-title a,
            .widget_recent_post .recent-post-list .post-info .post-title,
            .woocommerce .woocommerce-layout .finix-switch-layout a,
            .single-product .summary .price .amount,
            .single-product .summary .price del .amount,
            .single-product div.product .summary .product_meta > span,
            .woocommerce .site-content div.product .woocommerce-tabs ul.wc-tabs li a,
            .woocommerce ul.products li.product .product-block-inner .product-info .product-title a,
            .woocommerce ul.products li.product .product-block-inner .product-info .woocommerce-Price-amount,
            .woocommerce nav.woocommerce-pagination ul li a,
            .woocommerce nav.woocommerce-pagination ul li span,
            .woocommerce .site-content div.product .woocommerce-tabs .woocommerce-Tabs-panel h2,
            .woocommerce .woocommerce-Reviews #review_form_wrapper .comment-reply-title,
            .woocommerce .woocommerce-Reviews #review_form_wrapper .comment-form-rating .stars a,
            .woocommerce_status_bar .status-steps-item label,
            .woocommerce-cart table.shop_table th,
            .woocommerce-checkout .woocommerce-checkout table.shop_table th,
            .skill .progress-title,
            .portfolio-main .grid-item .item-info .portfolio-title .title-link,
            .single-portfolio .recent-portfolio .latest-portfolio .portfolio-content .portfolio-title a {color : $secondary_color; }"; 

        // Background Color
        $dynamic_css .="
            .xxx { color : $secondary_color; }"; 
    }

    // Tertiary Color
    if( !empty($tertiary_color)) {
        $dynamic_css .="
            body,
            .main-navigation .navbar-nav > li > a,
            .site-header .header-search .search-btn,
            .widget ul li > a,
            .widget.widget_recent_comments li.recentcomments .comment-author-link a {color : $tertiary_color; }";

        $dynamic_css .="
            .slicknav_menu .slicknav_icon-bar {background : $tertiary_color; }"; 
    }

    wp_add_inline_style( 'finix-responsive', $dynamic_css );
}
add_action( 'wp_enqueue_scripts', 'finix_color_customization', 20);
?>